@startuml

skinparam defaultTextAlignment center
skinparam padding 2

start

:Procura //""${bean}""//
em um escopo;

if (**page**?) then (\nsim)
elseif (**request**?) then (\nsim)
elseif (**session**?) then (\nsim)
elseif (**application**?) then (\nsim)
else (\n\nnão encontrado)
  : Utiliza //**""null""**// /
  stop
endif

:Utiliza //""${bean}""// /

stop

@enduml
