title: prof.wagnermacedo.com
lang: pt-BR
theme: jekyll-theme-cayman
google_analytics: UA-108802103-1

defaults:
  -
    scope:
      path: "2017-2/pjw"
    values:
      title: "Programação em Java para Web"
      description: "Fanese - 2017/2"
