@startuml

skinparam Class {
    FontStyle bold
    FontSize 15
    AttributeFontSize 17
    AttributeFontName Ubuntu Mono
}

class " FrontController  " as FC <<servlet>> {
    doGet()
    doPost()
}

abstract class " Command  " as CMD <<abstract>>

class " Command1  " <<concrete>> extends CMD {
    functionA()
    functionB()
}

class " Command2  " <<concrete>> extends CMD {
    functionX()
    functionY()
}

FC .right.> CMD : "               "

hide fields

@enduml
